### ISSUE TITLE
Are first letter effects different from middle letter effects?

### ISSUE THREAD

**Issue by CrumpLab** [CrumpLab/EntropyTyping#3]
![unknown](https://user-images.githubusercontent.com/4038982/41299513-97265090-6e31-11e8-9f54-089a7322244c.png)

Here's a graph plotting mean IKSI for against H (entropy) for all the letter positions and word_lengths. The colors only show letter position. 

If letter uncertainty completely determined typing speed for letters, then we might expect a less scattered plot, with mean IKSI lining up more systematically across the values of H.

There appears to be two groups of data. The dots for the first position letters all have longer IKSIs, whereas the dots for the letters in position 2-9 are mostly much faster (with the curious exception of 8 and 9). 

Perhaps there is some evidence here that first-letter slowing is not only determined by H. Letters in the first position do appear to correlate very well with H, but as a group they are all slower than the other letters. What are some plausible interpretations of this?

It would have been nice if variation in H explained both the first-letter slowing phenomena, and the mid-word slowing phenomena. It looks like might explain some of the variance in IKSI, and there are other things going on in addition to that.

**Comment by wlai0611** [comment]
If we want to see if the first letter delay is caused by syllable planning, how about we
 relate bigram frequency with the first letter IKSI.  So if bigram frequency is negatively correlated with IKSI
 the we can say that processing the next bigram is causing the delay, not H.

**Comment by CrumpLab** [comment]
Interesting ideas. One thing is that the above graph now looks quite different after we remove punctuation, spaces, capitals etc. as Nick suggested, so I'm going to close this thread so that we don't continue to think about this graph. But, the general issue is still worth thinking about so I'll open up another issue about this.
